/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package cumulative.poetry;

import org.junit.Test;
import static org.junit.Assert.*;

public class PoetTest {

    @Test
    public void recite()
    {
        Poet poet=new Poet();
        assertEquals("Day 1\n" +
                "This is the house that Jack built\n" +
                "\n" +
                "Day 2\n" +
                "This is the malth that lay in\n" +
                "\thouse that Jack built\n" +
                "\n" +
                "Day 3\n" +
                "This is the rat that ate\n" +
                "\tmalth that lay in\n" +
                "\thouse that Jack built\n" +
                "\n" +
                "Day 4\n" +
                "This is the cat that killed\n" +
                "\trat that ate\n" +
                "\tmalth that lay in\n" +
                "\thouse that Jack built\n" +
                "\n" +
                "Day 5\n" +
                "This is the dog that worried\n" +
                "\tcat that killed\n" +
                "\trat that ate\n" +
                "\tmalth that lay in\n" +
                "\thouse that Jack built\n" +
                "\n" +
                "Day 6\n" +
                "This is the cow with the crumpled horn that tossed\n" +
                "\tdog that worried\n" +
                "\tcat that killed\n" +
                "\trat that ate\n" +
                "\tmalth that lay in\n" +
                "\thouse that Jack built\n" +
                "\n" +
                "Day 7\n" +
                "This is the maiden all forlorn that milked\n" +
                "\tcow with the crumpled horn that tossed\n" +
                "\tdog that worried\n" +
                "\tcat that killed\n" +
                "\trat that ate\n" +
                "\tmalth that lay in\n" +
                "\thouse that Jack built\n" +
                "\n" +
                "Day 8\n" +
                "This is the man all tattered and torn that kissed\n" +
                "\tmaiden all forlorn that milked\n" +
                "\tcow with the crumpled horn that tossed\n" +
                "\tdog that worried\n" +
                "\tcat that killed\n" +
                "\trat that ate\n" +
                "\tmalth that lay in\n" +
                "\thouse that Jack built\n" +
                "\n" +
                "Day 9\n" +
                "This is the priest all shaven and shorn that married\n" +
                "\tman all tattered and torn that kissed\n" +
                "\tmaiden all forlorn that milked\n" +
                "\tcow with the crumpled horn that tossed\n" +
                "\tdog that worried\n" +
                "\tcat that killed\n" +
                "\trat that ate\n" +
                "\tmalth that lay in\n" +
                "\thouse that Jack built\n" +
                "\n" +
                "Day 10\n" +
                "This is the rooster that crowed in the morn that woke\n" +
                "\tpriest all shaven and shorn that married\n" +
                "\tman all tattered and torn that kissed\n" +
                "\tmaiden all forlorn that milked\n" +
                "\tcow with the crumpled horn that tossed\n" +
                "\tdog that worried\n" +
                "\tcat that killed\n" +
                "\trat that ate\n" +
                "\tmalth that lay in\n" +
                "\thouse that Jack built\n" +
                "\n" +
                "Day 11\n" +
                "This is the farmer sowing his corn that kept\n" +
                "\trooster that crowed in the morn that woke\n" +
                "\tpriest all shaven and shorn that married\n" +
                "\tman all tattered and torn that kissed\n" +
                "\tmaiden all forlorn that milked\n" +
                "\tcow with the crumpled horn that tossed\n" +
                "\tdog that worried\n" +
                "\tcat that killed\n" +
                "\trat that ate\n" +
                "\tmalth that lay in\n" +
                "\thouse that Jack built\n" +
                "\n" +
                "Day 12\n" +
                "This is the horse and the hound and the horn that belonged to\n" +
                "\tfarmer sowing his corn that kept\n" +
                "\trooster that crowed in the morn that woke\n" +
                "\tpriest all shaven and shorn that married\n" +
                "\tman all tattered and torn that kissed\n" +
                "\tmaiden all forlorn that milked\n" +
                "\tcow with the crumpled horn that tossed\n" +
                "\tdog that worried\n" +
                "\tcat that killed\n" +
                "\trat that ate\n" +
                "\tmalth that lay in\n" +
                "\thouse that Jack built\n",poet.recite());
    }

}
